# Generated by Django 5.2.8 on 2025-12-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='título')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('requisitos', models.TextField()),
                ('remuneracao', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='remuneração')),
                ('data_postagem', models.DateField()),
                ('data_final', models.DateField()),
            ],
        ),
    ]
