# Generated by Django 5.2.8 on 2025-12-02 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_vaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portifolio.aluno')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portifolio.vaga')),
            ],
        ),
    ]
